import { join } from 'node:path'
import { Archetype } from '@strav/database/schema/types'
import type { SchemaDefinition } from '@strav/database/schema/types'
import { toSnakeCase, toPascalCase, pluralize } from '@strav/kernel/helpers/strings'
import type { GeneratedFile } from './model_generator.ts'
import type { GeneratorConfig, GeneratorPaths, WriteResult } from './config.ts'
import { resolvePaths, relativeImport, formatAndWrite } from './config.ts'

/** Archetypes that sit under a parent's /:parentId group. */
const DEPENDENT_ARCHETYPES: Set<Archetype> = new Set([
  Archetype.Component,
  Archetype.Attribute,
  Archetype.Event,
  Archetype.Configuration,
  Archetype.Contribution,
])

// ---------------------------------------------------------------------------
// API routing config
// ---------------------------------------------------------------------------

export enum ApiRouting {
  Prefix = 'prefix',
  Subdomain = 'subdomain',
}

export interface ApiRoutingConfig {
  routing: ApiRouting
  prefix: string
  subdomain: string
}

const API_DEFAULTS: ApiRoutingConfig = {
  routing: ApiRouting.Prefix,
  prefix: '/api',
  subdomain: 'api',
}

// ---------------------------------------------------------------------------
// RouteGenerator
// ---------------------------------------------------------------------------

/**
 * Generate a `start/api_routes.ts` file that wires all non-association
 * schemas to the router using `router.resource()` — fully derived from
 * archetype and parent relationships.
 *
 * Routing mode (prefix vs subdomain) is read from `config/http.ts`.
 */
export default class RouteGenerator {
  private apiConfig: ApiRoutingConfig
  private paths: GeneratorPaths

  constructor(
    private schemas: SchemaDefinition[],
    config?: GeneratorConfig,
    apiConfig?: Partial<ApiRoutingConfig>
  ) {
    this.apiConfig = { ...API_DEFAULTS, ...apiConfig }
    this.paths = resolvePaths(config)
  }

  /** Generate the route file contents without writing to disk. */
  generate(): GeneratedFile[] {
    return [this.generateRouteFile()]
  }

  /** Generate, format with Prettier, and write the route file to disk. */
  async writeAll(force?: boolean): Promise<WriteResult> {
    const files = this.generate()
    return formatAndWrite(files, { force })
  }

  // ---------------------------------------------------------------------------
  // Core generation
  // ---------------------------------------------------------------------------

  private generateRouteFile(): GeneratedFile {
    const routable = this.schemas.filter(s => s.archetype !== Archetype.Association)

    // Group schemas by parent (null = root level)
    const childrenOf = new Map<string | null, SchemaDefinition[]>()
    for (const s of routable) {
      const parent = DEPENDENT_ARCHETYPES.has(s.archetype) ? (s.parents?.[0] ?? null) : null
      if (!childrenOf.has(parent)) childrenOf.set(parent, [])
      childrenOf.get(parent)!.push(s)
    }

    const lines: string[] = [
      '// Generated by Strav — DO NOT EDIT',
      `import { router } from '@strav/http/http'`,
      `import { auth } from '@strav/http/auth'`,
      '',
    ]

    // Controller imports (from barrel)
    const controllerImport = relativeImport(this.paths.routes, this.paths.controllers)
    const controllerNames = routable.map(s => toPascalCase(s.name) + 'Controller')
    lines.push(`import { ${controllerNames.join(', ')} } from '${controllerImport}'`)

    lines.push('')
    if (this.apiConfig.routing === ApiRouting.Subdomain) {
      lines.push(
        `router.group({ subdomain: '${this.apiConfig.subdomain}', middleware: [auth()] }, r => {`
      )
    } else {
      lines.push(
        `router.group({ prefix: '${this.apiConfig.prefix}', middleware: [auth()] }, r => {`
      )
    }

    // Root-level resources (entity, reference)
    const roots = childrenOf.get(null) ?? []
    for (const s of roots) {
      const className = toPascalCase(s.name) + 'Controller'
      const routePath = '/' + this.routeSegment(s.name)
      lines.push(`  r.resource('${routePath}', ${className})`)
    }

    // Parent groups — each parent with dependent children gets a group
    for (const [parentName, children] of childrenOf) {
      if (parentName === null) continue

      const parentSegment = this.routeSegment(parentName)

      lines.push('')
      lines.push(`  r.group({ prefix: '/${parentSegment}/:parentId' }, r => {`)

      for (const child of children) {
        const className = toPascalCase(child.name) + 'Controller'
        const childPath = '/' + this.childSegment(child.name, parentName)

        if (child.archetype === Archetype.Configuration) {
          lines.push(`    r.resource('${childPath}', ${className}).singleton()`)
        } else {
          lines.push(`    r.resource('${childPath}', ${className})`)
        }
      }

      lines.push(`  })`)
    }

    lines.push('})')
    lines.push('')

    return {
      path: join(this.paths.routes, 'api_routes.ts'),
      content: lines.join('\n'),
    }
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  private routeSegment(name: string): string {
    return toRouteSegment(name)
  }

  private childSegment(childName: string, parentName: string): string {
    return toChildSegment(childName, parentName)
  }
}

// ---------------------------------------------------------------------------
// Exported helpers (shared with TestGenerator)
// ---------------------------------------------------------------------------

/** Pluralized, hyphenated URL segment for a schema name. */
export function toRouteSegment(name: string): string {
  return pluralize(toSnakeCase(name)).replace(/_/g, '-')
}

/**
 * URL segment for a dependent schema, stripping the parent prefix when the
 * child name starts with the parent name (e.g. post_content → contents).
 */
export function toChildSegment(childName: string, parentName: string): string {
  const parentSnake = toSnakeCase(parentName)
  let childSnake = toSnakeCase(childName)

  if (childSnake.startsWith(parentSnake + '_')) {
    childSnake = childSnake.slice(parentSnake.length + 1)
  }

  return pluralize(childSnake).replace(/_/g, '-')
}
