import { describe, expect, test } from 'bun:test'
import { parseRawMail } from '../src/mail/inbound/raw_mail_parser.ts'

const CRLF = '\r\n'

function rfc822(lines: string[]): string {
  return lines.join(CRLF)
}

describe('parseRawMail', () => {
  test('parses a minimal RFC822 message', async () => {
    const raw = rfc822([
      'From: "Sender" <sender@example.com>',
      'To: "Support" <support@example.com>',
      'Subject: Hello',
      'Message-ID: <abc@example.com>',
      'Date: Thu, 05 Apr 2018 16:59:01 +0000',
      '',
      'Hello body',
    ])

    const result = await parseRawMail(raw)

    expect(result.from).toEqual({ address: 'sender@example.com', name: 'Sender' })
    expect(result.to).toEqual([{ address: 'support@example.com', name: 'Support' }])
    expect(result.subject).toBe('Hello')
    expect(result.text?.trim()).toBe('Hello body')
    expect(result.messageId).toBe('abc@example.com')
    expect(result.isAutoGenerated).toBe(false)
    expect(result.date).toBeInstanceOf(Date)
  })

  test('extracts In-Reply-To and References with angle brackets stripped', async () => {
    const raw = rfc822([
      'From: sender@example.com',
      'To: support@example.com',
      'Subject: Re: Thread',
      'Message-ID: <reply@example.com>',
      'In-Reply-To: <parent@example.com>',
      'References: <root@example.com> <parent@example.com>',
      '',
      'reply body',
    ])

    const result = await parseRawMail(raw)

    expect(result.inReplyTo).toBe('parent@example.com')
    expect(result.references).toEqual(['root@example.com', 'parent@example.com'])
  })

  test('detects auto-generated messages via Auto-Submitted', async () => {
    const raw = rfc822([
      'From: vacation@example.com',
      'To: support@example.com',
      'Subject: Out of office',
      'Auto-Submitted: auto-replied',
      '',
      'I am on vacation.',
    ])

    const result = await parseRawMail(raw)
    expect(result.isAutoGenerated).toBe(true)
  })

  test('detects auto-generated via Precedence: bulk', async () => {
    const raw = rfc822([
      'From: list@example.com',
      'To: support@example.com',
      'Subject: Newsletter',
      'Precedence: bulk',
      '',
      'Weekly news.',
    ])

    const result = await parseRawMail(raw)
    expect(result.isAutoGenerated).toBe(true)
  })

  test('extracts multiple To recipients', async () => {
    const raw = rfc822([
      'From: sender@example.com',
      'To: alice@example.com, bob@example.com',
      'Cc: carol@example.com',
      'Subject: Multi',
      '',
      'Hi all.',
    ])

    const result = await parseRawMail(raw)
    expect(result.to.map(t => t.address)).toEqual(['alice@example.com', 'bob@example.com'])
    expect(result.cc.map(c => c.address)).toEqual(['carol@example.com'])
  })

  test('parses multipart/mixed with text + html + attachment', async () => {
    const boundary = 'B0UND4RY'
    const base64Data = Buffer.from('attachment content', 'utf-8').toString('base64')
    const raw = rfc822([
      'From: sender@example.com',
      'To: recipient@example.com',
      'Subject: Mixed message',
      'MIME-Version: 1.0',
      `Content-Type: multipart/mixed; boundary="${boundary}"`,
      '',
      `--${boundary}`,
      'Content-Type: text/plain; charset=utf-8',
      '',
      'Plain part',
      `--${boundary}`,
      'Content-Type: text/html; charset=utf-8',
      '',
      '<p>HTML part</p>',
      `--${boundary}`,
      'Content-Type: text/plain; charset=utf-8',
      'Content-Disposition: attachment; filename="note.txt"',
      'Content-Transfer-Encoding: base64',
      '',
      base64Data,
      `--${boundary}--`,
      '',
    ])

    const result = await parseRawMail(raw)

    expect(result.text).toContain('Plain part')
    expect(result.html).toContain('HTML part')
    expect(result.attachments).toHaveLength(1)
    const [att] = result.attachments
    expect(att!.filename).toBe('note.txt')
    expect(att!.content.toString('utf-8')).toBe('attachment content')
    expect(att!.contentType).toBe('text/plain')
    expect(att!.size).toBeGreaterThan(0)
  })

  test('keeps raw header values in the headers map (lowercase keys)', async () => {
    const raw = rfc822([
      'From: sender@example.com',
      'To: support@example.com',
      'Subject: Header check',
      'X-Custom-Header: some-value',
      '',
      'body',
    ])

    const result = await parseRawMail(raw)
    expect(result.headers['x-custom-header']).toBe('some-value')
    expect(result.headers['from']).toBeDefined()
  })

  test('accepts Buffer input and produces identical shape', async () => {
    const raw = rfc822([
      'From: sender@example.com',
      'To: support@example.com',
      'Subject: Buffer',
      'Message-ID: <buf@example.com>',
      '',
      'body',
    ])

    const [fromString, fromBuffer] = await Promise.all([
      parseRawMail(raw),
      parseRawMail(Buffer.from(raw, 'utf-8')),
    ])

    expect(fromBuffer.messageId).toBe(fromString.messageId)
    expect(fromBuffer.from.address).toBe(fromString.from.address)
  })
})
