export { PostmarkInboundParser } from './postmark_parser.ts'
export { isAutoGeneratedMessage } from './loop_guard.ts'
export type {
  InboundWebhookInput,
  InboundWebhookParser,
  ParsedInboundAddress,
  ParsedInboundAttachment,
  ParsedInboundMail,
} from './types.ts'
