import { createHmac, timingSafeEqual } from 'node:crypto'
import { AuthenticationError, ConfigurationError, ExternalServiceError } from '@strav/kernel'
import type {
  InboundWebhookInput,
  InboundWebhookParser,
  MailgunInboundConfig,
  ParsedInboundAddress,
  ParsedInboundAttachment,
  ParsedInboundMail,
} from './types.ts'
import { isAutoGeneratedMessage } from './loop_guard.ts'

type DecodedForm = Awaited<ReturnType<Response['formData']>>

/**
 * Parse a Mailgun Routes inbound webhook payload.
 *
 * Mailgun POSTs multipart/form-data to the route URL. Authentication uses
 * HMAC-SHA256 over (timestamp + token) with the dashboard's webhook signing
 * key. Signature verification is mandatory here — call it through an HTTP
 * route that passes the raw body and content-type header unchanged.
 *
 * Throws AuthenticationError on signature mismatch or stale timestamp,
 * ExternalServiceError on malformed payloads.
 *
 * @see https://documentation.mailgun.com/docs/mailgun/user-manual/receive-forward-store/
 */
export class MailgunInboundParser implements InboundWebhookParser {
  private readonly signingKey: string
  private readonly maxAgeSeconds: number

  constructor(config: MailgunInboundConfig) {
    if (!config.webhookSigningKey) {
      throw new ConfigurationError('MailgunInboundParser requires webhookSigningKey')
    }
    this.signingKey = config.webhookSigningKey
    this.maxAgeSeconds = config.maxAgeSeconds ?? 300
  }

  async parse(input: InboundWebhookInput): Promise<ParsedInboundMail> {
    const contentType = input.headers['content-type'] ?? ''
    if (!contentType.toLowerCase().includes('multipart/')) {
      throw new ExternalServiceError(
        'Mailgun',
        400,
        `Expected multipart/form-data, got: ${contentType || '(none)'}`
      )
    }

    const form = await this.decodeMultipart(input.body, contentType)

    const signature = getField(form, 'signature')
    const token = getField(form, 'token')
    const timestamp = getField(form, 'timestamp')
    if (!signature || !token || !timestamp) {
      throw new AuthenticationError('Mailgun webhook missing signature/token/timestamp')
    }
    this.verifyTimestamp(timestamp)
    this.verifySignature(timestamp, token, signature)

    const headers = parseMessageHeaders(getField(form, 'message-headers'))

    const from = parseAddress(getField(form, 'from')) ?? {
      address: getField(form, 'sender') ?? '',
    }
    const to = parseAddressList(getField(form, 'recipient'))
    const cc = parseAddressList(headers['cc'])
    const replyTo = parseAddress(headers['reply-to'])

    return {
      from,
      to,
      cc,
      bcc: [],
      replyTo,
      subject: getField(form, 'subject') ?? '',
      text: getField(form, 'body-plain') || undefined,
      html: getField(form, 'body-html') || undefined,
      date: headers['date'] ? new Date(headers['date']) : undefined,
      headers,
      attachments: await extractAttachments(form),
      messageId: stripAngles(headers['message-id']),
      inReplyTo: stripAngles(headers['in-reply-to']),
      references: parseReferences(headers['references']),
      isAutoGenerated: isAutoGeneratedMessage(headers),
    }
  }

  private async decodeMultipart(body: string | Buffer, contentType: string): Promise<DecodedForm> {
    try {
      const payload = typeof body === 'string' ? Buffer.from(body, 'utf-8') : body
      const response = new Response(payload, { headers: { 'content-type': contentType } })
      return await response.formData()
    } catch (err) {
      throw new ExternalServiceError(
        'Mailgun',
        400,
        `Invalid multipart payload: ${(err as Error).message}`
      )
    }
  }

  private verifySignature(timestamp: string, token: string, signature: string): void {
    const expected = createHmac('sha256', this.signingKey)
      .update(timestamp + token)
      .digest('hex')

    // Constant-time compare — requires equal length, else timingSafeEqual throws.
    if (expected.length !== signature.length) {
      throw new AuthenticationError('Mailgun webhook signature mismatch')
    }
    const ok = timingSafeEqual(Buffer.from(expected, 'utf-8'), Buffer.from(signature, 'utf-8'))
    if (!ok) throw new AuthenticationError('Mailgun webhook signature mismatch')
  }

  private verifyTimestamp(timestamp: string): void {
    const ts = Number(timestamp)
    if (!Number.isFinite(ts)) {
      throw new AuthenticationError('Mailgun webhook: invalid timestamp')
    }
    const nowSec = Math.floor(Date.now() / 1000)
    if (Math.abs(nowSec - ts) > this.maxAgeSeconds) {
      throw new AuthenticationError('Mailgun webhook: timestamp outside allowed window')
    }
  }
}

function getField(form: DecodedForm, name: string): string | undefined {
  const value = form.get(name)
  if (value === null || value === undefined) return undefined
  return typeof value === 'string' ? value : undefined
}

function parseMessageHeaders(raw: string | undefined): Record<string, string> {
  if (!raw) return {}
  try {
    const pairs = JSON.parse(raw) as unknown
    if (!Array.isArray(pairs)) return {}
    const out: Record<string, string> = {}
    for (const entry of pairs) {
      if (!Array.isArray(entry) || entry.length < 2) continue
      const [name, value] = entry
      if (typeof name === 'string' && typeof value === 'string') {
        out[name.toLowerCase()] = value
      }
    }
    return out
  } catch {
    return {}
  }
}

async function extractAttachments(form: DecodedForm): Promise<ParsedInboundAttachment[]> {
  const count = Number(form.get('attachment-count') ?? 0)
  if (!Number.isFinite(count) || count <= 0) return []

  const result: ParsedInboundAttachment[] = []
  for (let i = 1; i <= count; i++) {
    const file = form.get(`attachment-${i}`)
    if (!file || typeof file === 'string') continue
    const content = Buffer.from(await file.arrayBuffer())
    result.push({
      filename: file.name || `attachment-${i}`,
      contentType: file.type || 'application/octet-stream',
      content,
      size: content.length,
    })
  }
  return result
}

function parseAddress(raw: string | undefined): ParsedInboundAddress | undefined {
  if (!raw) return undefined
  const trimmed = raw.trim()
  if (!trimmed) return undefined

  const match = trimmed.match(/^\s*(?:"?([^"<]*?)"?\s*)?<([^<>\s]+@[^<>\s]+)>\s*$/)
  if (match) {
    const name = match[1]?.trim()
    const address = match[2]!
    return name ? { address, name } : { address }
  }
  if (/^[^<>\s]+@[^<>\s]+$/.test(trimmed)) return { address: trimmed }
  return undefined
}

function parseAddressList(raw: string | undefined): ParsedInboundAddress[] {
  if (!raw) return []
  // Mailgun delivers To / recipient as a comma-separated list.
  return raw
    .split(',')
    .map(part => parseAddress(part))
    .filter((v): v is ParsedInboundAddress => v !== undefined)
}

function parseReferences(value: string | undefined): string[] {
  if (!value) return []
  return value
    .split(/\s+/)
    .map(r => stripAngles(r))
    .filter((v): v is string => Boolean(v))
}

function stripAngles(value: string | undefined): string | undefined {
  if (!value) return undefined
  const trimmed = value.trim()
  if (trimmed.startsWith('<') && trimmed.endsWith('>')) {
    const inner = trimmed.slice(1, -1).trim()
    return inner || undefined
  }
  return trimmed || undefined
}
