import { simpleParser, type AddressObject, type ParsedMail } from 'mailparser'
import type {
  ParsedInboundAddress,
  ParsedInboundAttachment,
  ParsedInboundMail,
} from './types.ts'
import { isAutoGeneratedMessage } from './loop_guard.ts'

/**
 * Convert raw RFC 5322 bytes into the canonical ParsedInboundMail shape.
 *
 * Used by the IMAP driver (message bodies arrive as raw bytes) and by any
 * consumer that has RFC822 in hand — e.g. webhook providers that forward the
 * raw source alongside their pre-parsed payload.
 */
export async function parseRawMail(source: Buffer | string): Promise<ParsedInboundMail> {
  const parsed = await simpleParser(source)
  const headers = buildHeadersMap(parsed)

  return {
    from: mapAddress(parsed.from) ?? { address: '' },
    to: mapAddressList(parsed.to),
    cc: mapAddressList(parsed.cc),
    bcc: mapAddressList(parsed.bcc),
    replyTo: mapAddress(parsed.replyTo),
    subject: parsed.subject ?? '',
    text: parsed.text || undefined,
    html: typeof parsed.html === 'string' ? parsed.html : undefined,
    date: parsed.date,
    headers,
    attachments: mapAttachments(parsed),
    messageId: stripAngles(parsed.messageId),
    inReplyTo: stripAngles(parsed.inReplyTo),
    references: normalizeReferences(parsed.references),
    isAutoGenerated: isAutoGeneratedMessage(headers),
  }
}

function buildHeadersMap(parsed: ParsedMail): Record<string, string> {
  const result: Record<string, string> = {}
  for (const line of parsed.headerLines) {
    const colonIdx = line.line.indexOf(':')
    if (colonIdx < 0) continue
    result[line.key.toLowerCase()] = line.line.slice(colonIdx + 1).trim()
  }
  return result
}

function mapAddress(addr: AddressObject | undefined): ParsedInboundAddress | undefined {
  if (!addr) return undefined
  const list = Array.isArray(addr) ? addr : [addr]
  const first = list[0]?.value[0]
  if (!first?.address) return undefined
  return first.name ? { address: first.address, name: first.name } : { address: first.address }
}

function mapAddressList(
  addr: AddressObject | AddressObject[] | undefined
): ParsedInboundAddress[] {
  if (!addr) return []
  const list = Array.isArray(addr) ? addr : [addr]
  const out: ParsedInboundAddress[] = []
  for (const item of list) {
    for (const value of item.value) {
      if (!value.address) continue
      out.push(value.name ? { address: value.address, name: value.name } : { address: value.address })
    }
  }
  return out
}

function mapAttachments(parsed: ParsedMail): ParsedInboundAttachment[] {
  return parsed.attachments.map(a => {
    const cid = a.cid ?? stripAngles(a.contentId)
    return {
      filename: a.filename ?? 'attachment',
      contentType: a.contentType ?? 'application/octet-stream',
      content: a.content,
      size: a.size,
      ...(cid ? { cid } : {}),
    }
  })
}

function normalizeReferences(refs: string | string[] | undefined): string[] {
  if (!refs) return []
  const list = Array.isArray(refs) ? refs : refs.split(/\s+/)
  return list.map(r => stripAngles(r)).filter((v): v is string => Boolean(v))
}

function stripAngles(value: string | undefined): string | undefined {
  if (!value) return undefined
  const trimmed = value.trim()
  if (trimmed.startsWith('<') && trimmed.endsWith('>')) {
    const inner = trimmed.slice(1, -1).trim()
    return inner || undefined
  }
  return trimmed || undefined
}
