/**
 * Inbound mail types.
 *
 * Provider webhooks (Postmark / SendGrid / Mailgun / SES) and the future IMAP
 * driver all normalize to ParsedInboundMail so application code can consume
 * inbound mail from any source uniformly.
 */

export interface ParsedInboundAddress {
  address: string
  name?: string
}

export interface ParsedInboundAttachment {
  filename: string
  contentType: string
  content: Buffer
  size: number
  /** Content-ID for inline images, angle brackets stripped. */
  cid?: string
}

export interface ParsedInboundMail {
  from: ParsedInboundAddress
  to: ParsedInboundAddress[]
  cc: ParsedInboundAddress[]
  bcc: ParsedInboundAddress[]
  replyTo?: ParsedInboundAddress
  subject: string
  text?: string
  html?: string
  date?: Date
  /**
   * Lowercased header name → value. Duplicate headers keep the last value;
   * widen to string | string[] if a future driver needs to preserve duplicates.
   */
  headers: Record<string, string>
  attachments: ParsedInboundAttachment[]
  /** RFC 5322 Message-ID of the inbound message, angle brackets stripped. */
  messageId?: string
  /** In-Reply-To header value, angle brackets stripped. */
  inReplyTo?: string
  /** References header parsed into a list, angle brackets stripped. */
  references: string[]
  /**
   * True if the message looks auto-generated (auto-reply, vacation, bulk, list).
   * Applications must not auto-respond when this is true — skipping this check
   * causes mail loops.
   */
  isAutoGenerated: boolean
  /** Provider's own message identifier (e.g. Postmark MessageID), if any. */
  providerMessageId?: string
}

export interface InboundWebhookInput {
  /** Raw request body. Buffer preferred so future signature checks can see the exact bytes. */
  body: string | Buffer
  /** Request headers. Keys should be lowercased by the caller. */
  headers: Record<string, string | undefined>
}

export interface InboundWebhookParser {
  parse(input: InboundWebhookInput): Promise<ParsedInboundMail>
}

// -- IMAP driver --------------------------------------------------------------

export type ImapAuth =
  /** Plain password auth. */
  | { user: string; pass: string }
  /**
   * OAuth2 XOAUTH2. Provide a short-lived access token (refresh it yourself before
   * calling poll()). Gmail and Microsoft 365 require this path when modern-auth is
   * enforced.
   */
  | { user: string; accessToken: string }

export interface ImapInboundConfig {
  host: string
  /** Default 993 (IMAPS). */
  port?: number
  /** Default true (IMAPS). Set false only for plain IMAP on 143. */
  secure?: boolean
  auth: ImapAuth
  /** Mailbox to poll. Default 'INBOX'. */
  mailbox?: string
  /** Maximum messages fetched per poll cycle. Default 50. */
  batchSize?: number
  /** Fetch and parse but do NOT mark \Seen. Useful for diagnostics. Default false. */
  dryRun?: boolean
  /** Forwarded to node:tls. Use only when you know what you're doing. */
  tls?: { rejectUnauthorized?: boolean }
}

export interface PollResult {
  /** Messages parsed + handler ran + marked \Seen. */
  processed: number
  /**
   * Handler threw (or the fetch failed) — the message is NOT marked \Seen,
   * so it will be retried on the next cycle.
   */
  failed: number
  /** Messages whose raw source could not be fetched (skipped, not retried). */
  skipped: number
}

export type InboundMailHandler = (mail: ParsedInboundMail) => void | Promise<void>

// -- Mailgun Routes webhook ---------------------------------------------------

export interface MailgunInboundConfig {
  /**
   * Mailgun "HTTP webhook signing key" from the dashboard — distinct from the
   * sending API key. Rotating it in the dashboard requires rotating here too.
   */
  webhookSigningKey: string
  /**
   * Reject signatures whose timestamp is older than N seconds. Default 300
   * (5 minutes). Tightens replay protection; widen only if clock skew is an issue.
   */
  maxAgeSeconds?: number
}
