export { default, default as SocialManager } from './social_manager.ts'

// Provider
export { default as SocialProvider } from './social_provider.ts'
export { default as SocialAccount } from './social_account.ts'
export { social } from './helpers.ts'
export { AbstractProvider, SocialError } from './abstract_provider.ts'
export { GoogleProvider } from './providers/google_provider.ts'
export { GitHubProvider } from './providers/github_provider.ts'
export { DiscordProvider } from './providers/discord_provider.ts'
export { FacebookProvider } from './providers/facebook_provider.ts'
export { LinkedInProvider } from './providers/linkedin_provider.ts'
export { LineProvider } from './providers/line_provider.ts'
export type { SocialUser, SocialConfig, ProviderConfig, TokenResponse } from './types.ts'
export type { SocialAccountData } from './social_account.ts'
